package com.example.ipcapp;

import android.view.Gravity;
import android.widget.PopupWindow;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import android.content.Intent;
import android.view.View;
import android.os.Bundle;
import android.widget.Button;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    private List<DataModel> mList;
    private ItemAdapter adapter;
    private Button chatButton;
    private Button showPopupButton;
    @Override
    protected void onCreate(Bundle savedInstanceState) {


        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);



        recyclerView = findViewById(R.id.main_recyclerview);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        mList = new ArrayList<>();

        Database d = new Database();
        //list1
        List<String> nestedList1 = new ArrayList<>();
        nestedList1.add(d.section_1);
        nestedList1.add(d.section_2);
        nestedList1.add(d.section_3);
        nestedList1.add(d.section_4);
        nestedList1.add(d.section_5);

        List<String> nestedList2 = new ArrayList<>();
        nestedList2.add(d.section_6);
        nestedList2.add(d.section_7);
        nestedList2.add(d.section_8);
        nestedList2.add(d.section_9);
        nestedList2.add(d.section_10);
        nestedList2.add(d.section_11);
        nestedList2.add(d.section_12);
        nestedList2.add(d.section_13);
        nestedList2.add(d.section_14);
        nestedList2.add(d.section_15);
        nestedList2.add(d.section_16);
        nestedList2.add(d.section_17);
        nestedList2.add(d.section_18);
        nestedList2.add(d.section_19);
        nestedList2.add(d.section_20);
        nestedList2.add(d.section_21);
        nestedList2.add(d.section_22);
        nestedList2.add(d.section_23);
        nestedList2.add(d.section_24);
        nestedList2.add(d.section_25);
        nestedList2.add(d.section_26);
        nestedList2.add(d.section_27);
        nestedList2.add(d.section_28);
        nestedList2.add(d.section_29);
        nestedList2.add(d.section_29A);
        nestedList2.add(d.section_30);
        nestedList2.add(d.section_31);
        nestedList2.add(d.section_32);
        nestedList2.add(d.section_33);
        nestedList2.add(d.section_34);
        nestedList2.add(d.section_35);
        nestedList2.add(d.section_36);
        nestedList2.add(d.section_37);
        nestedList2.add(d.section_38);
        nestedList2.add(d.section_39);
        nestedList2.add(d.section_40);
        nestedList2.add(d.section_41);
        nestedList2.add(d.section_42);
        nestedList2.add(d.section_43);
        nestedList2.add(d.section_44);
        nestedList2.add(d.section_45);
        nestedList2.add(d.section_46);
        nestedList2.add(d.section_47);
        nestedList2.add(d.section_48);
        nestedList2.add(d.section_49);
        nestedList2.add(d.section_50);
        nestedList2.add(d.section_51);
        nestedList2.add(d.section_52);
        nestedList2.add(d.section_52A);

        List<String> nestedList3 = new ArrayList<>();
        nestedList3.add(d.section_53);
        nestedList3.add(d.section_53A);
        nestedList3.add(d.section_54);
        nestedList3.add(d.section_55);
        nestedList3.add(d.section_55A);
        nestedList3.add(d.section_56);
        nestedList3.add(d.section_57);
        nestedList3.add(d.section_58);
        nestedList3.add(d.section_59);
        nestedList3.add(d.section_60);
        nestedList3.add(d.section_61);
        nestedList3.add(d.section_62);
        nestedList3.add(d.section_63);
        nestedList3.add(d.section_64);
        nestedList3.add(d.section_65);
        nestedList3.add(d.section_66);
        nestedList3.add(d.section_67);
        nestedList3.add(d.section_68);
        nestedList3.add(d.section_69);
        nestedList3.add(d.section_70);
        nestedList3.add(d.section_71);
        nestedList3.add(d.section_72);
        nestedList3.add(d.section_73);
        nestedList3.add(d.section_74);
        nestedList3.add(d.section_75);

        List<String> nestedList4 = new ArrayList<>();
        nestedList4.add(d.section_76);
        nestedList4.add(d.section_77);
        nestedList4.add(d.section_78);
        nestedList4.add(d.section_79);
        nestedList4.add(d.section_80);
        nestedList4.add(d.section_81);
        nestedList4.add(d.section_82);
        nestedList4.add(d.section_83);
        nestedList4.add(d.section_84);
        nestedList4.add(d.section_85);
        nestedList4.add(d.section_86);
        nestedList4.add(d.section_87);
        nestedList4.add(d.section_88);
        nestedList4.add(d.section_89);
        nestedList4.add(d.section_90);
        nestedList4.add(d.section_91);
        nestedList4.add(d.section_92);
        nestedList4.add(d.section_93);
        nestedList4.add(d.section_94);
        nestedList4.add(d.section_95);
        nestedList4.add(d.section_96);
        nestedList4.add(d.section_97);
        nestedList4.add(d.section_98);
        nestedList4.add(d.section_99);
        nestedList4.add(d.section_100);
        nestedList4.add(d.section_101);
        nestedList4.add(d.section_102);
        nestedList4.add(d.section_103);
        nestedList4.add(d.section_104);
        nestedList4.add(d.section_105);
        nestedList4.add(d.section_106);


        List<String> nestedList5 = new ArrayList<>();

        nestedList5.add(d.section_107);
        nestedList5.add(d.section_108);
        nestedList5.add(d.section_108A);
        nestedList5.add(d.section_109);
        nestedList5.add(d.section_110);
        nestedList5.add(d.section_111);
        nestedList5.add(d.section_112);
        nestedList5.add(d.section_113);
        nestedList5.add(d.section_114);
        nestedList5.add(d.section_115);
        nestedList5.add(d.section_116);
        nestedList5.add(d.section_117);
        nestedList5.add(d.section_118);
        nestedList5.add(d.section_119);
        nestedList5.add(d.section_120);


        List<String> nestedList5A = new ArrayList<>();

        nestedList5A.add(d.section_120A);
        nestedList5A.add(d.section_120B);


        List<String> nestedList6 = new ArrayList<>();
        nestedList6.add(d.section_121);
        nestedList6.add(d.section_121A);
        nestedList6.add(d.section_122);
        nestedList6.add(d.section_123);
        nestedList6.add(d.section_124);
        nestedList6.add(d.section_124A);
        nestedList6.add(d.section_125);
        nestedList6.add(d.section_126);
        nestedList6.add(d.section_127);
        nestedList6.add(d.section_128);
        nestedList6.add(d.section_129);
        nestedList6.add(d.section_130);


        List<String> nestedList7 = new ArrayList<>();
        nestedList7.add(d.section_131);
        nestedList7.add(d.section_132);
        nestedList7.add(d.section_133);
        nestedList7.add(d.section_134);
        nestedList7.add(d.section_135);
        nestedList7.add(d.section_136);
        nestedList7.add(d.section_137);
        nestedList7.add(d.section_138);
        nestedList7.add(d.section_138A);
        nestedList7.add(d.section_139);

        List<String> nestedList8 = new ArrayList<>();
        nestedList8.add(d.section_141);
        nestedList8.add(d.section_142);
        nestedList8.add(d.section_143);
        nestedList8.add(d.section_144);
        nestedList8.add(d.section_145);
        nestedList8.add(d.section_146);
        nestedList8.add(d.section_147);
        nestedList8.add(d.section_148);
        nestedList8.add(d.section_149);
        nestedList8.add(d.section_150);
        nestedList8.add(d.section_151);
        nestedList8.add(d.section_152);
        nestedList8.add(d.section_153);
        nestedList8.add(d.section_153A);
        nestedList8.add(d.section_153B);
        nestedList8.add(d.section_154);
        nestedList8.add(d.section_155);
        nestedList8.add(d.section_156);
        nestedList8.add(d.section_157);
        nestedList8.add(d.section_158);
        nestedList8.add(d.section_159);
        nestedList8.add(d.section_160);

        List<String> nestedList9 = new ArrayList<>();
        nestedList9.add(d.section_161);
        nestedList9.add(d.section_162);
        nestedList9.add(d.section_163);
        nestedList9.add(d.section_164);
        nestedList9.add(d.section_165);
        nestedList9.add(d.section_165A);
        nestedList9.add(d.section_166);
        nestedList9.add(d.section_166A);
        nestedList9.add(d.section_166B);
        nestedList9.add(d.section_167);
        nestedList9.add(d.section_168);
        nestedList9.add(d.section_169);
        nestedList9.add(d.section_170);
        nestedList9.add(d.section_171);

        List<String> nestedList9A = new ArrayList<>();
        nestedList9A.add(d.section_171);
        nestedList9A.add(d.section_171A);
        nestedList9A.add(d.section_171B);
        nestedList9A.add(d.section_171C);
        nestedList9A.add(d.section_171D);
        nestedList9A.add(d.section_171E);
        nestedList9A.add(d.section_171F);
        nestedList9A.add(d.section_171G);
        nestedList9A.add(d.section_171H);
        nestedList9A.add(d.section_171I);

        List<String> nestedList10 = new ArrayList<>();
        nestedList10.add(d.section_172);
        nestedList10.add(d.section_173);
        nestedList10.add(d.section_174);
        nestedList10.add(d.section_174A);
        nestedList10.add(d.section_175);
        nestedList10.add(d.section_176);
        nestedList10.add(d.section_177);
        nestedList10.add(d.section_178);
        nestedList10.add(d.section_179);
        nestedList10.add(d.section_180);
        nestedList10.add(d.section_181);
        nestedList10.add(d.section_182);
        nestedList10.add(d.section_183);
        nestedList10.add(d.section_184);
        nestedList10.add(d.section_185);
        nestedList10.add(d.section_186);
        nestedList10.add(d.section_187);
        nestedList10.add(d.section_188);
        nestedList10.add(d.section_189);
        nestedList10.add(d.section_190);

        List<String> nestedList11 = new ArrayList<>();
        nestedList11.add(d.section_191);
        nestedList11.add(d.section_192);
        nestedList11.add(d.section_193);
        nestedList11.add(d.section_194);
        nestedList11.add(d.section_195);
        nestedList11.add(d.section_195A);
        nestedList11.add(d.section_196);
        nestedList11.add(d.section_197);
        nestedList11.add(d.section_198);
        nestedList11.add(d.section_199);
        nestedList11.add(d.section_200);
        nestedList11.add(d.section_201);
        nestedList11.add(d.section_202);
        nestedList11.add(d.section_203);
        nestedList11.add(d.section_204);
        nestedList11.add(d.section_205);
        nestedList11.add(d.section_206);
        nestedList11.add(d.section_207);
        nestedList11.add(d.section_208);
        nestedList11.add(d.section_209);
        nestedList11.add(d.section_210);
        nestedList11.add(d.section_211);
        nestedList11.add(d.section_212);
        nestedList11.add(d.section_213);
        nestedList11.add(d.section_214);
        nestedList11.add(d.section_215);
        nestedList11.add(d.section_216);
        nestedList11.add(d.section_216A);
        nestedList11.add(d.section_216B);
        nestedList11.add(d.section_217);
        nestedList11.add(d.section_218);
        nestedList11.add(d.section_219);
        nestedList11.add(d.section_220);
        nestedList11.add(d.section_221);
        nestedList11.add(d.section_222);
        nestedList11.add(d.section_223);
        nestedList11.add(d.section_224);
        nestedList11.add(d.section_225);
        nestedList11.add(d.section_225A);
        nestedList11.add(d.section_226);
        nestedList11.add(d.section_227);
        nestedList11.add(d.section_228);
        nestedList11.add(d.section_228A);
        nestedList11.add(d.section_229);
        nestedList11.add(d.section_229A);

        List<String>nestedList12 = new ArrayList<>();
        nestedList12.add(d.section_230);
        nestedList12.add(d.section_231);
        nestedList12.add(d.section_232);
        nestedList12.add(d.section_233);
        nestedList12.add(d.section_234);
        nestedList12.add(d.section_235);
        nestedList12.add(d.section_236);
        nestedList12.add(d.section_237);
        nestedList12.add(d.section_238);
        nestedList12.add(d.section_239);
        nestedList12.add(d.section_240);
        nestedList12.add(d.section_241);
        nestedList12.add(d.section_242);
        nestedList12.add(d.section_243);
        nestedList12.add(d.section_244);
        nestedList12.add(d.section_245);
        nestedList12.add(d.section_246);
        nestedList12.add(d.section_247);
        nestedList12.add(d.section_248);
        nestedList12.add(d.section_249);
        nestedList12.add(d.section_250);
        nestedList12.add(d.section_251);
        nestedList12.add(d.section_252);
        nestedList12.add(d.section_253);
        nestedList12.add(d.section_254);
        nestedList12.add(d.section_255);
        nestedList12.add(d.section_256);
        nestedList12.add(d.section_257);
        nestedList12.add(d.section_258);
        nestedList12.add(d.section_259);
        nestedList12.add(d.section_260);
        nestedList12.add(d.section_261);
        nestedList12.add(d.section_262);
        nestedList12.add(d.section_263);
        nestedList12.add(d.section_263A);

        List<String> nestedList13 = new ArrayList<>();
        nestedList13.add(d.section_264);
        nestedList13.add(d.section_265);
        nestedList13.add(d.section_266);
        nestedList13.add(d.section_267);

        List<String> nestedList14 = new ArrayList<>();
        nestedList14.add(d.section_268);
        nestedList14.add(d.section_269);
        nestedList14.add(d.section_270);
        nestedList14.add(d.section_271);
        nestedList14.add(d.section_272);
        nestedList14.add(d.section_273);
        nestedList14.add(d.section_274);
        nestedList14.add(d.section_275);
        nestedList14.add(d.section_276);
        nestedList14.add(d.section_277);
        nestedList14.add(d.section_278);
        nestedList14.add(d.section_279);
        nestedList14.add(d.section_280);
        nestedList14.add(d.section_281);
        nestedList14.add(d.section_282);
        nestedList14.add(d.section_283);
        nestedList14.add(d.section_284);
        nestedList14.add(d.section_285);
        nestedList14.add(d.section_286);
        nestedList14.add(d.section_287);
        nestedList14.add(d.section_288);
        nestedList14.add(d.section_289);
        nestedList14.add(d.section_290);
        nestedList14.add(d.section_291);
        nestedList14.add(d.section_292);
        nestedList14.add(d.section_293);
        nestedList14.add(d.section_294);
        nestedList14.add(d.section_294A);

        List<String> nestedList15 = new ArrayList<>();
        nestedList15.add(d.section_295);
        nestedList15.add(d.section_295A);
        nestedList15.add(d.section_296);
        nestedList15.add(d.section_297);
        nestedList15.add(d.section_298);

        List<String> nestedList16 = new ArrayList<>();
        nestedList16.add(d.section_299);
        nestedList16.add(d.section_300);
        nestedList16.add(d.section_301);
        nestedList16.add(d.section_302);
        nestedList16.add(d.section_303);
        nestedList16.add(d.section_304);
        nestedList16.add(d.section_304A);
        nestedList16.add(d.section_304B);
        nestedList16.add(d.section_305);
        nestedList16.add(d.section_306);
        nestedList16.add(d.section_307);
        nestedList16.add(d.section_308);
        nestedList16.add(d.section_309);
        nestedList16.add(d.section_310);
        nestedList16.add(d.section_311);
        nestedList16.add(d.section_312);
        nestedList16.add(d.section_313);
        nestedList16.add(d.section_314);
        nestedList16.add(d.section_315);
        nestedList16.add(d.section_316);
        nestedList16.add(d.section_317);
        nestedList16.add(d.section_318);
        nestedList16.add(d.section_319);
        nestedList16.add(d.section_320);
        nestedList16.add(d.section_321);
        nestedList16.add(d.section_322);
        nestedList16.add(d.section_323);
        nestedList16.add(d.section_324);
        nestedList16.add(d.section_325);
        nestedList16.add(d.section_326);
        nestedList16.add(d.section_326A);
        nestedList16.add(d.section_326B);
        nestedList16.add(d.section_327);
        nestedList16.add(d.section_328);
        nestedList16.add(d.section_329);
        nestedList16.add(d.section_330);
        nestedList16.add(d.section_331);
        nestedList16.add(d.section_332);
        nestedList16.add(d.section_333);
        nestedList16.add(d.section_334);
        nestedList16.add(d.section_335);
        nestedList16.add(d.section_336);
        nestedList16.add(d.section_337);
        nestedList16.add(d.section_338);
        nestedList16.add(d.section_338);
        nestedList16.add(d.section_338);
        nestedList16.add(d.section_339);
        nestedList16.add(d.section_340);
        nestedList16.add(d.section_341);
        nestedList16.add(d.section_342);
        nestedList16.add(d.section_343);
        nestedList16.add(d.section_344);
        nestedList16.add(d.section_345);
        nestedList16.add(d.section_346);
        nestedList16.add(d.section_347);
        nestedList16.add(d.section_348);
        nestedList16.add(d.section_349);
        nestedList16.add(d.section_350);
        nestedList16.add(d.section_351);
        nestedList16.add(d.section_352);
        nestedList16.add(d.section_353);
        nestedList16.add(d.section_354);
        nestedList16.add(d.section_354A);
        nestedList16.add(d.section_354B);
        nestedList16.add(d.section_354C);
        nestedList16.add(d.section_354D);
        nestedList16.add(d.section_355);
        nestedList16.add(d.section_356);
        nestedList16.add(d.section_357);
        nestedList16.add(d.section_358);
        nestedList16.add(d.section_359);
        nestedList16.add(d.section_360);
        nestedList16.add(d.section_361);
        nestedList16.add(d.section_362);
        nestedList16.add(d.section_363);
        nestedList16.add(d.section_363A);
        nestedList16.add(d.section_364);
        nestedList16.add(d.section_365);
        nestedList16.add(d.section_366);
        nestedList16.add(d.section_366A);
        nestedList16.add(d.section_366B);
        nestedList16.add(d.section_367);
        nestedList16.add(d.section_368);
        nestedList16.add(d.section_369);
        nestedList16.add(d.section_370);
        nestedList16.add(d.section_370A);
        nestedList16.add(d.section_371);
        nestedList16.add(d.section_372);
        nestedList16.add(d.section_373);
        nestedList16.add(d.section_374);
        nestedList16.add(d.section_375);
        nestedList16.add(d.section_376);
        nestedList16.add(d.section_376A);
        nestedList16.add(d.section_376B);
        nestedList16.add(d.section_376C);
        nestedList16.add(d.section_376D);
        nestedList16.add(d.section_376E);
        nestedList16.add(d.section_377);

        List<String> nestedList17 = new ArrayList<>();
        nestedList17.add(d.section_378);
        nestedList17.add(d.section_379);
        nestedList17.add(d.section_380);
        nestedList17.add(d.section_381);
        nestedList17.add(d.section_382);
        nestedList17.add(d.section_383);
        nestedList17.add(d.section_384);
        nestedList17.add(d.section_85);
        nestedList17.add(d.section_386);
        nestedList17.add(d.section_387);
        nestedList17.add(d.section_388);
        nestedList17.add(d.section_389);
        nestedList17.add(d.section_390);
        nestedList17.add(d.section_391);
        nestedList17.add(d.section_392);
        nestedList17.add(d.section_393);
        nestedList17.add(d.section_394);
        nestedList17.add(d.section_395);
        nestedList17.add(d.section_396);
        nestedList17.add(d.section_397);
        nestedList17.add(d.section_398);
        nestedList17.add(d.section_399);
        nestedList17.add(d.section_400);
        nestedList17.add(d.section_401);
        nestedList17.add(d.section_402);
        nestedList17.add(d.section_403);
        nestedList17.add(d.section_404);
        nestedList17.add(d.section_405);
        nestedList17.add(d.section_406);
        nestedList17.add(d.section_407);
        nestedList17.add(d.section_408);
        nestedList17.add(d.section_409);
        nestedList17.add(d.section_410);
        nestedList17.add(d.section_411);
        nestedList17.add(d.section_412);
        nestedList17.add(d.section_413);
        nestedList17.add(d.section_414);
        nestedList17.add(d.section_415);
        nestedList17.add(d.section_416);
        nestedList17.add(d.section_417);
        nestedList17.add(d.section_418);
        nestedList17.add(d.section_419);
        nestedList17.add(d.section_420);
        nestedList17.add(d.section_421);
        nestedList17.add(d.section_422);
        nestedList17.add(d.section_423);
        nestedList17.add(d.section_424);
        nestedList17.add(d.section_425);
        nestedList17.add(d.section_426);
        nestedList17.add(d.section_427);
        nestedList17.add(d.section_428);
        nestedList17.add(d.section_429);
        nestedList17.add(d.section_430);
        nestedList17.add(d.section_431);
        nestedList17.add(d.section_432);
        nestedList17.add(d.section_433);
        nestedList17.add(d.section_434);
        nestedList17.add(d.section_435);
        nestedList17.add(d.section_436);
        nestedList17.add(d.section_437);
        nestedList17.add(d.section_438);
        nestedList17.add(d.section_439);
        nestedList17.add(d.section_440);
        nestedList17.add(d.section_441);
        nestedList17.add(d.section_442);
        nestedList17.add(d.section_443);
        nestedList17.add(d.section_444);
        nestedList17.add(d.section_445);
        nestedList17.add(d.section_446);
        nestedList17.add(d.section_447);
        nestedList17.add(d.section_448);
        nestedList17.add(d.section_449);
        nestedList17.add(d.section_450);
        nestedList17.add(d.section_451);
        nestedList17.add(d.section_452);
        nestedList17.add(d.section_453);
        nestedList17.add(d.section_454);
        nestedList17.add(d.section_455);
        nestedList17.add(d.section_456);
        nestedList17.add(d.section_457);
        nestedList17.add(d.section_458);
        nestedList17.add(d.section_459);
        nestedList17.add(d.section_460);
        nestedList17.add(d.section_461);
        nestedList17.add(d.section_462);

        List<String> nestedList18 = new ArrayList<>();
        nestedList18.add(d.section_463);
        nestedList18.add(d.section_464);
        nestedList18.add(d.section_465);
        nestedList18.add(d.section_466);
        nestedList18.add(d.section_467);
        nestedList18.add(d.section_468);
        nestedList18.add(d.section_469);
        nestedList18.add(d.section_470);
        nestedList18.add(d.section_471);
        nestedList18.add(d.section_472);
        nestedList18.add(d.section_473);
        nestedList18.add(d.section_474);
        nestedList18.add(d.section_475);
        nestedList18.add(d.section_476);
        nestedList18.add(d.section_477);
        nestedList18.add(d.section_477A);
        nestedList18.add(d.section_478);
        nestedList18.add(d.section_479);
        nestedList18.add(d.section_480);
        nestedList18.add(d.section_481);
        nestedList18.add(d.section_482);
        nestedList18.add(d.section_483);
        nestedList18.add(d.section_484);
        nestedList18.add(d.section_485);
        nestedList18.add(d.section_486);
        nestedList18.add(d.section_487);
        nestedList18.add(d.section_488);
        nestedList18.add(d.section_489);
        nestedList18.add(d.section_489A);
        nestedList18.add(d.section_489B);
        nestedList18.add(d.section_489C);
        nestedList18.add(d.section_489D);
        nestedList18.add(d.section_489E);
        List<String> nestedList19 = new ArrayList<>();
        nestedList19.add(d.section_490);
        nestedList19.add(d.section_491);
        nestedList19.add(d.section_492);

        List<String> nestedList20 = new ArrayList<>();
        nestedList20.add(d.section_493);
        nestedList20.add(d.section_494);
        nestedList20.add(d.section_495);
        nestedList20.add(d.section_496);
        nestedList20.add(d.section_496);
        nestedList20.add(d.section_497);
        nestedList20.add(d.section_498);

        List<String> nestedList20A = new ArrayList<>();
        nestedList20A.add(d.section_498A);

        List<String> nestedList21 = new ArrayList<>();
        nestedList21.add(d.section_499);
        nestedList21.add(d.section_500);
        nestedList21.add(d.section_501);
        nestedList21.add(d.section_502);

        List<String> nestedList22 = new ArrayList<>();
        nestedList22.add(d.section_503);
        nestedList22.add(d.section_504);
        nestedList22.add(d.section_505);
        nestedList22.add(d.section_506);
        nestedList22.add(d.section_507);
        nestedList22.add(d.section_508);
        nestedList22.add(d.section_509);
        nestedList22.add(d.section_510);

        List<String> nestedList23 = new ArrayList<>();
        nestedList23.add(d.section_511);

        mList.add(new DataModel(nestedList1, "CHAPTER-1(1-5) "));
        mList.add(new DataModel(nestedList2, "CHAPTER-2(6-52A)"));
        mList.add(new DataModel(nestedList3, "CHAPTER-3(53-75)"));
        mList.add(new DataModel(nestedList4, "CHAPTER-4(76-106)"));
        mList.add(new DataModel(nestedList5, "CHAPTER-5(107-120)"));
        mList.add(new DataModel(nestedList5A, "CHAPTER-5A(120A-120B)"));
        mList.add(new DataModel(nestedList6, "CHAPTER-6(121-130)"));
        mList.add(new DataModel(nestedList7, "CHAPTER-7(131-140)"));
        mList.add(new DataModel(nestedList8, "CHAPTER-8(141-160)"));
        mList.add(new DataModel(nestedList9, "CHAPTER-9(161-171)"));
        mList.add(new DataModel(nestedList9A, "CHAPTER-9A(171A-171)"));
        mList.add(new DataModel(nestedList10, "CHAPTER-10(172-190)"));
        mList.add(new DataModel(nestedList11, "CHAPTER-11(191-229A)"));
        mList.add(new DataModel(nestedList12, "CHAPTER-12(230-263A)"));
        mList.add(new DataModel(nestedList13, "CHAPTER-13(264-267)"));
        mList.add(new DataModel(nestedList14, "CHAPTER-14(268-294A)"));
        mList.add(new DataModel(nestedList15, "CHAPTER-15(295-298)"));
        mList.add(new DataModel(nestedList16, "CHAPTER-16(299-377)"));
        mList.add(new DataModel(nestedList17, "CHAPTER-17(378-462)"));
        mList.add(new DataModel(nestedList18, "CHAPTER-18(463-489E)"));
        mList.add(new DataModel(nestedList19, "CHAPTER-19(490-492)"));
        mList.add(new DataModel(nestedList20, "CHAPTER-20(493-498)"));
        mList.add(new DataModel(nestedList20A, "CHAPTER-20A(498A)"));
        mList.add(new DataModel(nestedList21, "CHAPTER-21(499-502)"));
        mList.add(new DataModel(nestedList22, "CHAPTER-22(503-510)"));
        mList.add(new DataModel(nestedList23, "CHAPTER-23(511)"));


        adapter = new ItemAdapter(mList);
        recyclerView.setAdapter(adapter);

        chatButton = findViewById(R.id.chatButton);
        chatButton.setOnClickListener(view -> {
            Intent intent = new Intent(MainActivity.this, ChatbotMainActivity.class);
            startActivity(intent);
        });

    }

}
